### ISSUE TITLE
Integration-Testing: Infrastruktur

### ISSUE THREAD

**Issue by automatix** [dbsystel/AutoFIT#234]
## Beschreibung

Es soll alles Notwendige für die Erstellung und Ausführung von Integrationstests sowie deren Verknüpfung mit dem CI-Prozess (bzw. Jenkins) gemacht werden.

## Tasks

- [x] Struktur der Test-Verzeichnisse
- [x] Anpassung der Test-Konfiguration (`phpunit.xml`)
  - [x] LOCAL
  - [x] TEST
  - [x] PROD
- [x] Datenbank-Setup-Logik implementieren
- [x] Erstellung der Test-Datenbank
  - [x] LOCAL
  - [x] TEST
  - [x] PROD
- [x] Erstellung der SQL-Skripte fürs Datenbank-Setup
  - [x] `schema.sql`
  - [x] `stored-procedures.sql`
    - [x] `DELIMITER`-Problem lösen!
  - [x] `schema.sql`
- [x] Basis-Test-Klassen implementieren
- [x] <strike>Integration mit der IDE (mit Kurzanleitung für einsteigende Kollegen)</strike> Gestrichen bzw. verschoben in die IDE-Einführung.
- [x] Anpassung der Jenkins-Konfiguration (`build.xml`)
  - [x] LOCAL
  - [x] TEST
  - [x] PROD
- [x] Anpassung der PHP-Konfiguration (`php.ini`) (`MySQLi`)
  - [x] TEST
  - [x] PROD

**Comment by mw-ft** [comment]
IK: Das kann ich nicht einschätzen. Wir müssen mal zusammen sehen, was hier nun wie und wann getestet wird.
